COOK.validNodes = {
    ["en"] = {
        -- "Ashtree",
        -- "Aspect Rune",
        "Backpack",
        "Barrel",
        "Barrel (Burnt)",
        "Barrels",
        "Barrels (Burnt)",
        "Basket",
        -- "Beech",
        -- "Birch",
        -- "Blessed Thistle",
        "Book",
        "Book Stack",
        "Books",
        "Bookshelf",
        "Bottle",
        "Bottles",
        "Bread",
        -- "Bugloss",
        "Cabinet",
        -- "Calcinium Ore", -- Verified
        "Carrots",
        "Cheese",
        -- "Columbine",
        -- "Corn Flower",
        -- "Cotton",
        "Crate",
        "Crate (Burnt)",
        "Crates",
        "Crates (Burnt)",
        "Cup",
        "Cupboard",
        "Cups",
        "Desk",
        -- "Dragonthorn",
        "Dresser",
        "Drink",
        -- "Dwarven Ore",
        -- "Ebonthread",
        -- "Ebony Ore",
        -- "Emetic Russula",
        -- "Entoloma",
        -- "Essence Rune",
        -- "Famin Flower",
        "Fish",
        -- "Flax",
        "Food",
        -- "Galatite Ore",
        "Goblet",
        "Grain",
        "Grapes",
        "Heavy Sack",
        -- "Hickory",
        -- "High Iron Ore",
        -- "Imp Stool",
        -- "Iron Ore",
        -- "Iron Weed",
        "Jar",
        "Jug",
        -- "Jute",
        -- "Kreshweed",
        -- "Lady's Smock",
        -- "Luminous Russula",
        -- "Mahogany",
        -- "Maple",
        -- "Moonstone Ore",
        -- "Mountain Flower",
        "Mug",
        -- "Namira's Rot",
        "Nightstand",
        -- "Nightwood",
        -- "Nirnroot",
        -- "Oak",
        -- "Orichalc Ore", -- Needs Verification
        -- "Orichalcum Ore",
        "Pot",
        -- "Potency Rune",
        "Produce",
        -- "Pure Water",
        -- "QA Clickable",
        -- "QA Clickable Apples",
        -- "QA lowlevel provision test",
        -- "Quicksilver Ore",
        "Radish",
        "Sack",
        -- "Saint's Hair",
        -- "Silverweed",
        -- "Spidersilk",
        -- "Stinkhorn",
        "Tomb Urn",
        "Trunk",
        "Urn",
        "Vase",
        -- "Violet Copninus",
        -- "Void Bloom",
        -- "Voidstone Ore",
        "Wardrobe",
        -- "Water Hyacinth",
        -- "Water Skin",
        -- "White Cap",
        "Wine Rack",
        -- "Wormwood",
        -- "Yew",
    },
    ["de"] = {
        -- "Eschenholz",
        -- "Aspektrune",
        "Rucksack",
        "Fass",
        "Fass (versengt)",
        "Fässer",
        "Fässer (versengt)",
        "Korb",
        -- "Buche",
        -- "Birke",
        -- "Benediktenkraut",
        "Buch",
        "Buchstapel",
        "Bücher",
        "Bücherregal",
        "Flasche",
        "Flaschen",
        "Brot",
        -- "Wolfsauge",
        "Schrank",
        -- "Kalciniumerz",
        "Möhren",
        "Käse",
        -- "Akelei",
        -- "Kornblume",
        -- "Baumwolle",
        "Kiste",
        "Kiste (versengt)",
        "Kisten",
        "Kisten (versengt)",
        "Tasse",
        "Schrank",
        "Tassen",
        "Schreibtisch",
        -- "Drachendorn",
        "Kommode",
        "Getränk",
        -- "Dwemererz",
        -- "Ebenseide",
        -- "Ebenerz",
        -- "Speitäubling",
        -- "Glöckling",
        -- "Essenzrune",
        -- "Hungersnotblume",
        "Fischen",
        -- "Flachs",
        "Essen",
        -- "Galatiterz",
        "Becher",
        "Getreide",
        "Weintrauben",
        "Schwerer Sack",
        -- "Hickoryholz",
        -- "Feineisenerz",
        -- "Koboldschemel",
        -- "Eisenerz",
        -- "Eisenkraut",
        "Gefäß",
        "Krug",
        -- "Jute", -- Verified, it's just Jute
        -- "Kreshweed",
        -- "Wiesenschaumkraut",
        -- "Leuchttäubling",
        -- "Mahagoniholz",
        -- "Ahornholz",
        -- "Mondsteinerz",
        -- "Bergblume",
        "Becher",
        -- "Namira's Fäulnis",
        "Nachttisch",
        -- "Nachtholz",
        -- "Nirnwurz",
        -- "Eiche",
        -- "Orichalc Ore", -- Needs Verification
        -- "Oreichalkoserz", -- Orichalcum Ore
        "Topf",
        -- "Machtrune",
        "Produkt",
        -- "Reines Wasser",
        -- "QA Clickable",
        -- "QA Clickable Apples",
        -- "QA lowlevel provision test",
        -- "Quicksilver Ore",
        "Radieschen",
        "Sack",
        -- "Heiliges Haar",
        -- "Silverweed",
        -- "Spinnenseide",
        -- "Stinkmorchel",
        "Urnengrab",
        "Stamm", -- Needs Verification
        "Urne",
        "Vase",
        -- "Violetter Coprinus",
        -- "Leere Blüte",
        -- "Leerensteinerz",
        "Kleiderschrank",
        -- "Wasserhyazinthe",
        -- "Wasserhaut",
        -- "Weiße Kappe",
        "Weinregal",
        -- "Wermut",
        -- "Eibenholz",
    },
    -- Pot, Jute, Jar, Hickory, Grain, Cabinet and Entoloma are the same names in French
    ["fr"] = {
        -- "Frêne",
        -- "Rune d'Aspect",
        "Sac à dos",
        "Tonneau",
        "Tonneau (brûlé)",
        "Tonneaux",
        "Tonneaux (brûlés)",
        "Panier",
        -- "Hêtre",
        -- "Bouleau",
        -- "Chardon Béni",
        "Livre",
        "Pile de livres",
        "Livres",
        "Étagère",
        "Bouteille",
        "Bouteilles",
        "Pain",
        -- "Noctuelle",
        "Cabinet",
        -- "Minerai de Calcinium",
        "Carrottes",
        "Fromage",
        -- "Ancolie",
        -- "Bleuet",
        -- "Coton",
        "Caisse",
        "Caisse (brûlée)",
        "Caisses",
        "Caisses (brûlées)",
        "Tasse",
        "Commode",
        "Tasses",
        "Bureau",
        -- "Épine-de-Dragon",
        "Buffet",
        "Boisson",
        -- "Minerai Dwemer",
        -- "Fil d'Ebonite",
        -- "Minerai d'Ebonite",
        -- "Russule Emetique",
        -- "Entoloma",
        -- "Rune D'essence",
        -- "Famin Flower",
        "Poisson",
        -- "Lin",
        "Nourriture",
        -- "Minerai de Galatite",
        "Chope",
        "Grain",
        "Raisin",
        "Sac Lourd",
        -- "Hickory",
        -- "Minerai de Fer Noble",
        -- "Pied-de-Lutin",
        -- "Minerai de Fer",
        -- "Herbe de fer",
        "Jar",
        "Pichet",
        -- "Jute",
        -- "Fibre de Kresh",
        -- "Cardamine des Prés",
        -- "Russule Phosphorescente",
        -- "Acajou",
        -- "Érable",
        -- "Pierre de lune",
        -- "Lys des Cimes",
        "Choppe",
        -- "Truffe de Namira",
        "Table de chevet",
        -- "Bois de nuit",
        -- "Nirnrave",
        -- "Chêne",
        -- "Orichalc Ore", -- Needs Verification
        -- "Minerai D'orichalque",  -- Orichalcum Ore
        "Pot",
        -- "Rune de Puissance",
        "Céréales",
        -- "Eau Pure",
        -- "QA Clickable",
        -- "QA Clickable Apples",
        -- "QA lowlevel provision test",
        -- "Quicksilver Ore",
        "Radis",
        "Sac",
        -- "Saint's Hair",
        -- "Herbe d'argent",
        -- "Toile D'araignée",
        -- "Mutinus Elégans",
        "Urne tombale",
        "Coffre",
        "Urne",
        "Vase",
        -- "Coprin Violet",
        -- "Tissu de Vide",
        -- "Minerai de Pierre de Vide",
        "Garde-robe",
        -- "Jacinthe D'eau",
        -- "Outre d'Eau",
        -- "Chapeau Blanc",
        "Casier ŕ bouteilles",
        -- "Absinthe",
        -- "If",
    }
}

COOK.NodeArray = {
        { itemID = 26802, nodeName = {}, itemName = "Tomato" },
        { itemID = 26954, nodeName = {}, itemName = "Salt" },
        { itemID = 26962, nodeName = {}, itemName = "Pepper" },
        { itemID = 26966, nodeName = {}, itemName = "Drippings" },
        { itemID = 26974, nodeName = {}, itemName = "Cooking Fat" },
        { itemID = 26975, nodeName = {}, itemName = "Suet" },
        { itemID = 26976, nodeName = {}, itemName = "Lard" },
        { itemID = 26977, nodeName = {}, itemName = "Fatback" },
        { itemID = 26978, nodeName = {}, itemName = "Pinguis" },
        { itemID = 26986, nodeName = {}, itemName = "Thin Broth" },
        { itemID = 26987, nodeName = {}, itemName = "Broth" },
        { itemID = 26988, nodeName = {}, itemName = "Stock" },
        { itemID = 26989, nodeName = {}, itemName = "Jus" },
        { itemID = 26990, nodeName = {}, itemName = "Glace Viande" },
        { itemID = 26998, nodeName = {}, itemName = "Imperial Stock" },
        { itemID = 26999, nodeName = {}, itemName = "Meal" },
        { itemID = 27000, nodeName = {}, itemName = "Milled Flour" },
        { itemID = 27001, nodeName = {}, itemName = "Sifted Flour" },
        { itemID = 27002, nodeName = {}, itemName = "Cake Flour" },
        { itemID = 27003, nodeName = {}, itemName = "Baker's Flour" },
        { itemID = 27004, nodeName = {}, itemName = "Imperial Flour" },
        { itemID = 27035, nodeName = {}, itemName = "Hops" },
        { itemID = 27043, nodeName = {}, itemName = "Hallertau Hops" },
        { itemID = 27044, nodeName = {}, itemName = "Saaz Hops" },
        { itemID = 27048, nodeName = {}, itemName = "White Grapes" },
        { itemID = 27049, nodeName = {}, itemName = "Concord Grapes" },
        { itemID = 27051, nodeName = {}, itemName = "Jazbay Grapes" },
        { itemID = 27052, nodeName = {}, itemName = "Juniper Berry" },
        { itemID = 27053, nodeName = {}, itemName = "Canis Root" },
        { itemID = 27057, nodeName = {}, itemName = "Barley" },
        { itemID = 27058, nodeName = {}, itemName = "Red Wheat" },
        { itemID = 27059, nodeName = {}, itemName = "Oats" },
        { itemID = 27063, nodeName = {}, itemName = "Potato" },
        { itemID = 27064, nodeName = {}, itemName = "Onion" },
        { itemID = 27100, nodeName = {}, itemName = "Garlic" },
        { itemID = 28603, nodeName = {}, itemName = "Goat Meat" },
        { itemID = 28604, nodeName = {}, itemName = "Kwama Eggs" },
        { itemID = 28605, nodeName = {}, itemName = "Scuttle Meat" },
        { itemID = 28606, nodeName = {}, itemName = "Plump Worms" },
        { itemID = 28607, nodeName = {}, itemName = "Plump Rodent Toes" },
        { itemID = 28608, nodeName = {}, itemName = "Plump Maggots" },
        { itemID = 28609, nodeName = {}, itemName = "Chaurus Meat" },
        { itemID = 28610, nodeName = {}, itemName = "Frog Legs" },
        { itemID = 28632, nodeName = {}, itemName = "Snake Slime" },
        { itemID = 28634, nodeName = {}, itemName = "Snake Venom" },
        { itemID = 28635, nodeName = {}, itemName = "Wild honey" },
        { itemID = 28636, nodeName = {}, itemName = "Dragon's-Tongue Sap" },
        { itemID = 28637, nodeName = {}, itemName = "Sujamma Berries" },
        { itemID = 28638, nodeName = {}, itemName = "River Grapes" },
        { itemID = 28639, nodeName = {}, itemName = "Ash Millet" },
        { itemID = 28666, nodeName = {}, itemName = "Snowberry" },
        { itemID = 29030, nodeName = {}, itemName = "Comberry" },
        { itemID = 33752, nodeName = {}, itemName = "Capon Meat" },
        { itemID = 33753, nodeName = {}, itemName = "Battaglir Weeds" },
        { itemID = 33754, nodeName = {}, itemName = "Bear Haunch" },
        { itemID = 33755, nodeName = {}, itemName = "Flank Steak" },
        { itemID = 33756, nodeName = {}, itemName = "Combwort" },
        { itemID = 33757, nodeName = {}, itemName = "Venison" },
        { itemID = 33758, nodeName = {}, itemName = "Horker Meat" },
        { itemID = 33767, nodeName = {}, itemName = "Shornhelm Grains" },
        { itemID = 33768, nodeName = {}, itemName = "Iron Peat" },
        { itemID = 33769, nodeName = {}, itemName = "Tangerine" },
        { itemID = 33770, nodeName = {}, itemName = "Wasp Squeezings" },
        { itemID = 33771, nodeName = {}, itemName = "Dark Bile" },
        { itemID = 33772, nodeName = {}, itemName = "Orc Hops" },
        { itemID = 33773, nodeName = {}, itemName = "Desert Heather" },
        { itemID = 33774, nodeName = {}, itemName = "Black Tea" },
        { itemID = 34304, nodeName = {}, itemName = "Pork" },
        { itemID = 34305, nodeName = {}, itemName = "Guar Eggs" },
        { itemID = 34306, nodeName = {}, itemName = "Sweetmeats" },
        { itemID = 34307, nodeName = {}, itemName = "Liver" },
        { itemID = 34308, nodeName = {}, itemName = "Goat Bits" },
        { itemID = 34309, nodeName = {}, itemName = "Moon Sugar" },
        { itemID = 34311, nodeName = {}, itemName = "Crawdad" },
        { itemID = 34312, nodeName = {}, itemName = "Saltrice" },
        { itemID = 34321, nodeName = {}, itemName = "Beef" },
        { itemID = 34322, nodeName = {}, itemName = "Shank" },
        { itemID = 34323, nodeName = {}, itemName = "Mudcrab Meat" },
        { itemID = 34324, nodeName = {}, itemName = "Honey Comb" },
        { itemID = 34329, nodeName = {}, itemName = "Aged Meat" },
        { itemID = 34330, nodeName = {}, itemName = "Dusk Beetle" },
        { itemID = 34331, nodeName = {}, itemName = "Ripe Apple" },
        { itemID = 34332, nodeName = {}, itemName = "Wisp Floss" },
        { itemID = 34333, nodeName = {}, itemName = "Pig's Milk" },
        { itemID = 34334, nodeName = {}, itemName = "Glitter Eock" },
        { itemID = 34335, nodeName = {}, itemName = "Molasses" },
        { itemID = 34336, nodeName = {}, itemName = "Spring Wssence" },
        { itemID = 34345, nodeName = {}, itemName = "Crystal Berry" },
        { itemID = 34346, nodeName = {}, itemName = "Kaveh Beans" },
        { itemID = 34347, nodeName = {}, itemName = "Mountain Berries" },
        { itemID = 34348, nodeName = {}, itemName = "Bervez Fruit" },
        { itemID = 34349, nodeName = {}, itemName = "Jazbay Grapes" },
        { itemID = 40260, nodeName = {}, itemName = "Brown Malt" },
        { itemID = 40261, nodeName = {}, itemName = "Amber Malt" },
        { itemID = 40262, nodeName = {}, itemName = "Caramalt" },
        { itemID = 40263, nodeName = {}, itemName = "Wheat Malt" },
        { itemID = 40264, nodeName = {}, itemName = "White Malt" },
        { itemID = 40265, nodeName = {}, itemName = "Wine Grapes" },
        { itemID = 40266, nodeName = {}, itemName = "Grasa Grapes" },
        { itemID = 40267, nodeName = {}, itemName = "Lado Grapes" },
        { itemID = 40268, nodeName = {}, itemName = "Camaralet Grapes" },
        { itemID = 40269, nodeName = {}, itemName = "Ribier Grapes" },
        { itemID = 40270, nodeName = {}, itemName = "Corn Mash" },
        { itemID = 40271, nodeName = {}, itemName = "Wheat Mash" },
        { itemID = 40272, nodeName = {}, itemName = "Oat Mash" },
        { itemID = 40273, nodeName = {}, itemName = "Barley Mash" },
        { itemID = 40274, nodeName = {}, itemName = "Rice Mash" },
        { itemID = 40276, nodeName = {}, itemName = "Mutton Flank" },
        { itemID = 45522, nodeName = {}, itemName = "Imperial Mash" },
        { itemID = 45523, nodeName = {}, itemName = "Emperor Grapes" },
        { itemID = 45524, nodeName = {}, itemName = "Golden Malt" },
}

function COOK.GetItemNameFromItemID(id)
    for tsId, tsData in pairs(COOK.NodeArray) do
        --d("Id : " .. tsData.itemID)
        --d("Name : " .. tsData.itemName)
        if tsData.itemID == id then
            return tsData.itemName
        end
    end
    return nil
end

function COOK.GetTradeskillByMaterial(id)
    id = tonumber(id)
    for tsId, tsData in pairs(COOK.NodeArray) do
        if tsData.itemID == id then
            return true
        end
    end
    return false
end

function COOK.IsValidNode(name)
    for k, v in pairs(COOK.validNodes[COOK.language]) do
        if string.lower(v) == string.lower(name) then
            return true
        end
    end

    return false
end
